[project]
name = "converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.1",
    "requests>=2.32.4",
    "scipy>=1.16.0",
    "trimesh>=4.7.1",
]
